### ISSUE TITLE
Add support for NGA-East

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#124]
NGA-East will be implemented as a MultiGroundMotionModel in that it produces multiple median and sigma values. It consists of ~29 individual lookup-table based models derived from a slightly smaller set of  'seed' models. Each model is associated with a period-dependent weight (the individual models are largely meaningless on their own), and sigma consists of a 3-branch logic tree, the values of which must each be paired with each model (3 x 29 curves for total mean model). There are a variety of sigma models; for the time being we are going to implement the 'global' model.

Items for consideration:
* Grouped models: Sammons map rings or quadrants
* Deaggregation complicated by multiple medians. Run sensitivity tests to determine if  weighted median differs significantly from deaggregation across all individual models.

**Comment by pmpowers-usgs** [comment]
We are also going to create grouped models. For example, just the central (Sammons map) model with full weight, the models in the first ring with appropriately scaled weights, the models out to the second ring, etc...

Multiple median ground motions also complicates deaggregation. We should consider doing a sensitivity analysis wherein we check whether deaggregation results change drastically if each sub-model is deaggregated or if the weighted median is used alone for each source. In terms of calculating epsilon, sigma is the same across all models so perhaps the latter approach will be adequate and may therefore simplify implementation.

**Comment by pmpowers-usgs** [comment]
Preliminary implementation complete in #151 

###### Caveats:
* Cluster analysis is inconsistent in that it is performed after combining models, not before
* Deagg currently uses weight-averaged means; this is incorrect, or at least requires more study to determine if it generates an acceptable approximation

###### TODOs:
* MultiScalarGroundMotion needs array protection; use DataArrays instead
* Determine how to avoid using `instance` checking of ScalarGroundMotion types

**Comment by pmpowers-usgs** [comment]
- [ ] Investgate issues above
- [ ] Seed models as model group
- [ ] site amp #257 
- [ ] phiS2S update

**Comment by pmpowers-usgs** [comment]
Sigma model needs cleanup and consolidation:
 - [ ] GMM: 2014 composite model with wt-avgd `μ` and `σ`
 - [ ] Remove central-`σ` branch

For the time being we will continue to collapse the site term logic tree. `MultiScalarGroundMotion` already handles mixed `μ` and `σ`, with weights, but #326 is required for proper implementation.

**Comment by pmpowers-usgs** [comment]
* Final edits to NGA-East in PR's #405 and #403 
* Code to support numerous sensitivity tests added in prior PRs #387, #384, #383, #382, and #381

Closeout:
- [ ] Unit tests
- [ ] Tag repo
- [ ] Remove sensitivity code in [NGA-East](../blob/master/src/gov/usgs/earthquake/nshmp/gmm/NgaEastUsgs_2017.java)
- [ ] Remove NGA-East [hybrid models](../blob/master/src/gov/usgs/earthquake/nshmp/gmm/NgaEastHybrid.java)
- [ ] Deprecate, but don't remove [CombinedGMM](../blob/master/src/gov/usgs/earthquake/nshmp/gmm/CombinedGmm.java)
- [ ] Cleanup siteamp coeffs

**Comment by pmpowers-usgs** [comment]
Completed in #406 #407 #408
